version: '3.5'
services:
  mysql:
    image: mysql:8.0.28
    container_name: di_inter_tech_mysql
    environment:
      - MYSQL_DATABASE=login_db
      - MYSQL_USER=webuser
      - MYSQL_PASSWORD=webpass
      - MYSQL_ROOT_PASSWORD=rootpass
      - TZ=EEST
    ports:
      - "3306:3306"
    networks:
      - di_internet_technologies_network

  informatics:
    image: informatics:latest
    container_name: informatics
    environment:
      - db_host=mysql
      - db_user=webuser
      - db_password=webpass
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - di_internet_technologies_network

networks:
  di_internet_technologies_network:
    name: di_internet_technologies_network
    driver: bridge
  db_data:
  new_db_data:
